export interface CraftDetails {
  annual_revenue: string
  global_export: string
  artisans: string
  market_growth: string
  quality_rating: string
  sustainability: string
  market_share: string
  product_range: string
  customer_satisfaction: string
  avg_production_time: string
  energy_efficiency: string
  innovation_index: string
}

export interface Subcategory {
  name: string
  id: string
  details: CraftDetails
}

export interface Category {
  name: string
  id: string
  subcategories: Subcategory[]
}

export const categories: Category[] = [
  {
    name: "Boutique",
    id: "cat1",
    subcategories: [
      {
        name: "Pashmina",
        id: "pashmina",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Cashmere",
        id: "cashmere",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Kani",
        id: "kani",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Silk",
        id: "silk",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Sarongs",
        id: "sarongs",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Bags & Purses",
        id: "bags",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Jackets",
        id: "jackets",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Kaftans",
        id: "kaftans",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Kurtas",
        id: "kurtas",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Pherans",
        id: "pherans",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Jewelry",
        id: "jewelry",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
    ],
  },
  {
    name: "Interior Décor",
    id: "cat2",
    subcategories: [
      {
        name: "Papier-Mache",
        id: "papierMachie",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Tapestry",
        id: "tapestry",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Jeweled Wall Hangings",
        id: "jeweled",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Office Accessories",
        id: "officeAcc",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Room Divider Screens",
        id: "roomDividerSec",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Sofa and Cushion Covers",
        id: "sofaCushion",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Bed Linens",
        id: "bedLinens",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
    ],
  },
  {
    name: "Dining & Serving Ware",
    id: "cat3",
    subcategories: [
      {
        name: "Papermachieware",
        id: "papermachieware", // Corrected: Removed leading space
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Walnutware",
        id: "walnutware",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Silverware",
        id: "silverware",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Copperware",
        id: "copperware",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
    ],
  },
  {
    name: "Rugs and Carpets",
    id: "cat4",
    subcategories: [
      {
        name: "Rugs and Carpets",
        id: "rugs",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Namda Embroidery Rugs",
        id: "namda",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
    ],
  },
  {
    name: "Furniture",
    id: "cat5",
    subcategories: [
      {
        name: "Walnut Wood Carving Furniture",
        id: "walnut",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Crewel Upholstered Furniture",
        id: "crewel",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Wicker Furniture",
        id: "wicker",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Room Dividers",
        id: "roomDivider",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
    ],
  },
  {
    name: "Ceiling Treatment",
    id: "cat6",
    subcategories: [
      {
        name: "Ceiling Treatment (Khatamband)",
        id: "ceiling",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
    ],
  },
  {
    name: "Window Treatment",
    id: "cat7",
    subcategories: [
      {
        name: "Pinjrakari - Kashmir Lattice Work",
        id: "pinjrakari",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Crewel - Embroidery Curtains",
        id: "crewel_embroi",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
    ],
  },
  {
    name: "Recycled Craft",
    id: "cat8",
    subcategories: [
      {
        name: "Papier-Mache",
        id: "papier-machie",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Gabba",
        id: "gabba",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
    ],
  },
  {
    name: "Sports Craft",
    id: "cat9",
    subcategories: [
      {
        name: "Circket-Bat",
        id: "circketBag",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Chess-Board",
        id: "chess-board",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
    ],
  },
  {
    name: "Hide Craft",
    id: "cat10",
    subcategories: [
      {
        name: "Leather",
        id: "leather",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Fur & Astrakhan",
        id: "astrakhan",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
    ],
  },
  {
    name: "Culinary Craft",
    id: "cat11",
    subcategories: [
      {
        name: "Kashmiri Wazwan Canned Food",
        id: "wazwan",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Kahwa & Pink Tea",
        id: "kahwa",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
    ],
  },
  {
    name: "Embriodery",
    id: "cat12",
    subcategories: [
      {
        name: "Suzani/Sozni - Fine Needlework",
        id: "sozni",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Zardozi -- Metal Thread Work",
        id: "zardozi",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Zalakdozi - Crewel Work",
        id: "zalakdozi",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Ari/Aari - Hook Work",
        id: "aari",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Dorukh - Double-sided Work",
        id: "dorukh",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Kashidakari - Surface Embroidery",
        id: "kashidakari",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Jaaldar - Net Work",
        id: "jaaldar",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
      {
        name: "Papier-Machie Inspired Embriodery",
        id: "paperMachieInspired",
        details: {
          annual_revenue: "$160M+",
          global_export: "78%",
          artisans: "88000+",
          market_growth: "17% YoY",
          quality_rating: "4.8/5",
          sustainability: "96%",
          market_share: "30%",
          product_range: "80+",
          customer_satisfaction: "97%",
          avg_production_time: "60 Days",
          energy_efficiency: "95%",
          innovation_index: "4.6/5",
        },
      },
    ],
  },
]
