export const validateGSTNumber = (_gst: string): string => ""
export const validateStateSalesTaxPermit = (_permit: string): string => ""
export const validateTaxIdVendor = (_taxId: string): string => ""
export const validateEIN = (_ein: string): string => ""
export const validateImportExportCode = (_code: string): string => ""
export const validateUSImportExporter = (_code: string): string => ""
export const validateIFSCCode = (_ifsc: string): string => ""
export const validateABARoutingNumber = (_routing: string): string => ""

export const validateFieldByRole = (_fieldName: string, _value: string, _userRole: "vendor" | "buyer"): string => ""
