
import VerticalHeroSlider from "@/components/Essentials/VerticalBanner"
import { Users, Target, DollarSign, Shield } from "lucide-react"
import InsidePartnership from "@/components/Essentials/InsidePartnership"

export default function Page() {
  // Data for HomePage component
  const homePageData = {
    heroTitle: "Swift Partnership Activation",
    heroDescription: `Expand your reach and minimize risk with De Koshur Crafts' Consignment Partnership in the USA. This partnership allows you to display your products in premium retail spaces while retaining ownership until the products are sold. With our expert guidance, we handle everything from inventory management to logistics, ensuring your products reach the right audience in top U.S. locations. Our consignment model offers flexibility and reducing upfront costs, providing you with the opportunity to test the U.S. market and scale at your own pace while benefiting from our extensive network and industry expertise.`,

    // Dynamic Accordion Data
    accordionData: [
      {
        id: "item-1",
        title: "Core Drop Shipping Capabilities",
        content: [
          "Cloud-Based Infrastructure",
          "Advanced Search & Filters",
          "Personalized Recommendations",
          "Real-Time Product Availability",
          "Omnichannel Content Delivery",
          "Multi-Device Accessibility",
          "Geolocation Integration",
          "AI-Driven Personalization",
          "Scalable Infrastructure",
          "PWA Support",
        ],
        icon: "users",
      },
      {
        id: "item-2",
        title: "Payment & Transaction Features",
        content: [
          "Multiple Payment Methods",
          "Flexible Payment Plans",
          "Secure Payment Gateways",
          "Currency & Location Support",
          "Real-Time Shipping Costs",
          "Invoice Generation",
          "Transaction History",
          "Sales Tax Transparency",
          "Promo Codes Applied",
          "Payment Confirmation Notifications",
        ],
        icon: "heartHandshake",
      },
      {
        id: "item-3",
        title: "Security Features",
        content: [
          "PCI Compliance",
          "MFA",
          "Data Encryption",
          "Intrusion Detection",
          "Fraud Detection",
          "WAF Protection",
          "Secure Account Creation",
          "Privacy Compliance",
          "Identity Protection",
          "Continuous Monitoring",
        ],
        icon: "graduationCap",
      },
      {
        id: "item-4",
        title: "Marketing Features",
        content: [
          "Personalized Recommendations",
          "Targeted Email Marketing",
          "Behavioral Targeting",
          "Multi-Channel Marketing",
          "Campaign Analytics",
          "Predictive Analytics",
          "Geographic Segmentation",
          "Seasonal Promotions",
          "Dynamic Content",
          "Referral Program",
        ],
        icon: "stethoscope",
      },
      {
        id: "item-5",
        title: "Drop Shipping Partnership",
        content: [
          "No Inventory Risk",
          "Direct Shipping",
          "Seamless Integration",
          "Wide Product Selection",
          "Minimal Investment",
          "Global Reach",
          "Order Fulfillment Management",
          "Scalable Growth",
          "Automated Shipping Notifications",
          "Simplified Returns",
        ],
        icon: "building2",
      },
      {
        id: "item-6",
        title: "Private Label Partnership",
        content: [
          "Branding Control",
          "Exclusive Products",
          "Custom Packaging",
          "Increase Brand Recognition",
          "Higher Margins",
          "Vendor Support",
          "Global Distribution",
          "Product Customization",
          "Long-Term Partnership",
          "Flexible Orders",
        ],
        icon: "leaf",
      },
      {
        id: "item-7",
        title: "Additional Customer Engagement Formats",
        content: [
          "Digital Catalogs",
          "Lookbooks",
          "Product Videos",
          "Virtual Try-Ons",
          "3D Product Configurators",
          "Live Product Demos",
          "Customer Review Galleries",
          "User-Generated Content",
          "Personalized Product Recommendations",
          "Interactive Infographics",
        ],
        icon: "factory",
      },
      {
        id: "item-8",
        title: "Customer Financing Options",
        content: [
          "Store-Branded Credit Cards",
          "Installment Payment Plans",
          "Buy Now, Pay Later",
          "Lease-to-Own Programs",
          "Layaway Plans",
          "Deferred Interest Financing",
          "Custom Financing",
          "Pre-Approved Credit",
          "Flexible Schedules",
          "Zero-Interest Offers",
        ],
        icon: "globe2",
      },
    ],

    // Dynamic Comparison Data
    comparisonData: [
      {
        solution: "De Koshur Crafts",
        icon: <Users className="w-6 h-6" />,
        color: "bg-[var(--secondary-hover-color)]",
        features: {
          "Breadth of Handicraft Products": "Extensive Handicraft Product Offerings",
          "Kashmir Heritage Focus": "Strong emphasis on craftsmanship",
          "Kashmir Entire Product Line": "Full Kashmir Craft Representation",
          "Seller Verification": "Thorough Process",
          "Artisan Support": "High Artisan Support",
          "GI Tags/Certifications": "Prominent GI Certification for products",
          "Origin Traceability": "Detailed blockchain traceability",
          "Fair Trade Policies": "Integrated fair trade policies",
          "Eco-friendly Practices": "Strong focus on eco-friendly practices",
          "Cultural Storytelling": "Rich visual storytelling of artisan culture",
          "Multimedia Content": "Extensive multimedia content",
          "Personalized Suggestions": "Highly curated, seasonal collections",
          "Thematic Collections": "Seasonal and festival-based collections",
          "Pricing Transparency": "Fully transparent pricing for products",
          "Value-Added Services": "Tailored artisan resources logistics",
          "International Shipping": "Available for artisans and buyers",
          "B2B Networking": "Extensive networking opportunities",
          "Customer Education": "Extensive resources for buyers",
          "Return Policies": "Flexible return policies",
          "Brand Trust": "High, focused on craftsmanship",
          "Influencer Partnerships": "Planned influencer partnerships",
        },
      },
      {
        solution: "EPROLO",
        icon: <Target className="w-6 h-6" />,
        color: "bg-[var(--secondary-hover-color)]",
        features: {
          "Breadth of Handicraft Products": "Broad range of artisan products",
          "Kashmir Heritage Focus": "Minimal emphasis on heritage",
          "Kashmir Entire Product Line": "No representation",
          "Seller Verification": "Moderate verification of sellers",
          "Artisan Support": "Moderate artisan support",
          "GI Tags/Certifications": "No GI certifications",
          "Origin Traceability": "Limited traceability",
          "Fair Trade Policies": "Minimal fair trade policies",
          "Eco-friendly Practices": "Moderate eco-friendly efforts",
          "Cultural Storytelling": "Limited cultural storytelling",
          "Multimedia Content": "Limited multimedia content",
          "Personalized Suggestions": "Limited suggestions",
          "Thematic Collections": "Seasonal collections",
          "Pricing Transparency": "Transparent pricing model",
          "Value-Added Services": "Business credit, promotional discounts",
          "International Shipping": "Available for global buyers",
          "B2B Networking": "B2B networking opportunities",
          "Customer Education": "Moderate educational resources",
          "Return Policies": "Flexible return policies for buyers",
          "Brand Trust": "Moderate trust with artisan vendors",
          "Influencer Partnerships": "No focus on influencer partnerships",
        },
      },
      {
        solution: "Modalyst",
        icon: <DollarSign className="w-6 h-6" />,
        color: "bg-[var(--secondary-hover-color)]",
        features: {
          "Breadth of Handicraft Products": "On-demand products",
          "Kashmir Heritage Focus": "No emphasis on heritage",
          "Kashmir Entire Product Line": "Limited to on-demand items",
          "Seller Verification": "Verified sellers with on-demand",
          "Artisan Support": "Limited artisan support",
          "GI Tags/Certifications": "No GI certifications",
          "Origin Traceability": "Traceability based on-demand",
          "Fair Trade Policies": "Optional fair trade practices",
          "Eco-friendly Practices": "Focused on sustainable materials",
          "Cultural Storytelling": "No cultural storytelling",
          "Multimedia Content": "Limited multimedia content",
          "Personalized Suggestions": "Personalized based on preferences",
          "Thematic Collections": "Limited collections",
          "Pricing Transparency": "Transparent pricing for products",
          "Value-Added Services": "Custom on-demand services",
          "International Shipping": "Global shipping available",
          "B2B Networking": "Limited networking opportunities",
          "Customer Education": "Moderate educational resources",
          "Return Policies": "Return policies",
          "Brand Trust": "Moderate trust with on-demand",
          "Influencer Partnerships": "No focus on influencer partnerships",
        },
      },
      {
        solution: "Spocket",
        icon: <Shield className="w-6 h-6" />,
        color: "bg-[var(--secondary-hover-color)]",
        features: {
          "Breadth of Handicraft Products": "Product offerings",
          "Kashmir Heritage Focus": "No heritage focus",
          "Kashmir Entire Product Line": "Limited to dropshipping items",
          "Seller Verification": "Moderate seller checks",
          "Artisan Support": "Limited artisan support",
          "GI Tags/Certifications": "No GI certifications",
          "Origin Traceability": "Traceability",
          "Fair Trade Policies": "Optional fair trade policies",
          "Eco-friendly Practices": "Focus on eco-friendly suppliers",
          "Cultural Storytelling": "No cultural storytelling",
          "Multimedia Content": "Limited multimedia content",
          "Personalized Suggestions": "Personalized based on dropshipping",
          "Thematic Collections": "Seasonal and niche collections",
          "Pricing Transparency": "Transparent pricing",
          "Product sourcing integration": "Product sourcing integration",
          "Global shipping available": "Global shipping available",
          "Networking within dropshipping": "Networking within dropshipping",
          "Limited educational resources": "Limited educational resources",
          "Flexible returns based on dropshipping": "Flexible returns based on dropshipping",
          "Moderate trust with suppliers": "Moderate trust with suppliers",
          "No focus on influencer partnerships": "No focus on influencer partnerships",
        },
      },
      {
        solution: "CJDropshipping",
        icon: <Shield className="w-6 h-6" />,
        color: "bg-[var(--secondary-hover-color)]",
        features: {
          "Breadth of Handicraft Products": "Customizable Product Range",
          "Kashmir Heritage Focus": "Low Heritage Emphasis",
          "Kashmir Entire Product Line": "No Comprehensive Products",
          "Seller Verification": "Low Seller Verification",
          "Artisan Support": "No Artisan Support",
          "GI Tags/Certifications": "No GI Certifications",
          "Minimal Traceability": "Minimal Traceability",
          "No Fair Policies": "No Fair Policies",
          "Low Practices": "Low Practices",
          "No-Cultural Storytelling": "No-Cultural Storytelling",
          "Minimal Content": "Minimal Content",
          "Variable Suggestions": "Variable Suggestions",
          "Minimal Thematic": "Minimal Thematic",
          "Variable Transparency": "Variable Transparency",
          "Variable Services": "Variable Services",
          "Variable Shipping": "Variable Shipping",
          "Variable Support": "Variable Support",
          "Low Business Networking": "Low Business Networking",
          "No Engagement Forums": "No Engagement Forums",
          "Limited Education": "Limited Education",
          "Variable Return Policies": "Variable Return Policies",
        },
      },
    ],

    // Dynamic Advantages Data
    hexagonalAdvantages: [
      {
        number: "01",
        title: "Authenticity Guaranteed",
        description:
          "Buyers can confidently purchase genuine Kashmiri handicrafts, knowing that each product is certified for authenticity and high-quality craftsmanship.",
        color: "bg-[var(--secondary-color)]",
      },
      {
        number: "02",
        title: "Exclusive Selection",
        description:
          "Enjoy access to a curated collection of unique, handmade products that showcase the rich cultural heritage of Kashmir, not available in mass markets.",
        color: "bg-[var(--secondary-color)]",
      },
      {
        number: "03",
        title: "Convenient Shopping Experience",
        description:
          "Global shipping options make it easy to purchase authentic Kashmiri handicrafts from anywhere, simplifying your experience.",
        color: "bg-[var(--secondary-color)]",
      },
      {
        number: "04",
        title: "Support for Artisans",
        description:
          "Buyers contribute to the sustainable livelihoods of local artisans, promoting fair trade practices and preserving traditional crafts.",
        color: "bg-[var(--secondary-color)]",
      },
      {
        number: "05",
        title: "Economic Empowerment",
        description:
          "Connecting artisans with global markets, the platform drives sustainable economic growth, enhancing livelihoods and community opportunities.",
        color: "bg-[var(--secondary-color)]",
      },
      {
        number: "06",
        title: "Heritage Preservation",
        description:
          "The platform plays a key role in preserving and promoting Kashmiri craftsmanship, ensuring these traditional skills are passed down to future generations.",
        color: "bg-[var(--secondary-color)]",
      },
      {
        number: "07",
        title: "Increased Global Visibility",
        description:
          "Providing a global stage, the platform boosts Kashmiri crafts' reputation, driving demand for unique, high-quality, authentic products.",
        color: "bg-[var(--secondary-color)]",
      },
      {
        number: "08",
        title: "Sustainability",
        description:
          "Fostering eco-friendly practices and ethical production, the platform supports sustainable handicrafts and environmentally-conscious consumer choices.",
        color: "bg-[var(--secondary-color)]",
      },
    ],

    // Dynamic Cost Comparison Data
    costComparison: [
      {
        feature: "Platform Cost",
        deKoshurCrafts: "Free for Early Adopters",
        eprolo: "Free for Buyers",
        modalyst: "Free for Buyers",
        spocket: "Free for Buyers",
        cjdropshipping: "Free for Buyers",
      },
      {
        feature: "Subscription Fees",
        deKoshurCrafts: "None",
        eprolo: "No monthly fee",
        modalyst: "No monthly fee",
        spocket: "No monthly fee",
        cjdropshipping: "No monthly fee",
      },
      {
        feature: "Transaction Fees",
        deKoshurCrafts: "1.5%",
        eprolo: "15% commission fee",
        modalyst: "Based on product cost & shipping",
        spocket: "Based on product cost & shipping",
        cjdropshipping: "Based on product cost & shipping",
      },
      {
        feature: "Payment Processing Fees",
        deKoshurCrafts: "None",
        eprolo: "2.9% + $0.30",
        modalyst: "None",
        spocket: "2.9% + $0.30",
        cjdropshipping: "2.9% + $0.30",
      },
      {
        feature: "Product Cost",
        deKoshurCrafts: "Competitive pricing",
        eprolo: "Varies, set by the vendor",
        modalyst: "Based on on-demand model",
        spocket: "Varies, set by the vendor",
        cjdropshipping: "Varies, set by the vendor",
      },
      {
        feature: "Shipping Fees",
        deKoshurCrafts: "Paid by buyer",
        eprolo: "Paid by buyer",
        modalyst: "Paid by buyer",
        spocket: "Paid by buyer",
        cjdropshipping: "Paid by buyer",
      },
      {
        feature: "GI Certification Support",
        deKoshurCrafts: "Available for artisan products",
        eprolo: "Not available",
        modalyst: "Not applicable",
        spocket: "Not available",
        cjdropshipping: "Not available",
      },
      {
        feature: "Marketing Tools",
        deKoshurCrafts: "Subsidized support & digital tools",
        eprolo: "Discount and promotional tools",
        modalyst: "Limited marketing tools",
        spocket: "Limited marketing tools",
        cjdropshipping: "Limited marketing tools",
      },
      {
        feature: "Return Costs",
        deKoshurCrafts: "Buyer responsibility",
        eprolo: "Buyer responsibility",
        modalyst: "Buyer responsibility",
        spocket: "Buyer responsibility",
        cjdropshipping: "Buyer responsibility",
      },
      {
        feature: "Loyalty Rewards",
        deKoshurCrafts: "Available",
        eprolo: "No",
        modalyst: "No",
        spocket: "No",
        cjdropshipping: "No",
      },
      {
        feature: "Blockchain Traceability",
        deKoshurCrafts: "Included for all products",
        eprolo: "Not available",
        modalyst: "Not available",
        spocket: "Not available",
        cjdropshipping: "Not available",
      },
      {
        feature: "Custom Branding",
        deKoshurCrafts: "Available for all vendors",
        eprolo: "No",
        modalyst: "Available",
        spocket: "Available",
        cjdropshipping: "Available",
      },
      {
        feature: "Multimedia Storytelling",
        deKoshurCrafts: "Available for artisan stories",
        eprolo: "No",
        modalyst: "No",
        spocket: "No",
        cjdropshipping: "No",
      },
      {
        feature: "Eco-Friendly Practices",
        deKoshurCrafts: "Integrated with platform",
        eprolo: "Not emphasized",
        modalyst: "Available for certain products",
        spocket: "Not emphasized",
        cjdropshipping: "Not emphasized",
      },
    ],

    // Dynamic Pricing Plans Data
    pricingPlans: [
      {
        name: "Starter Plan",
        price: { monthly: 30, yearly: 360 },
        earlyAdopters: "1-20",
        features: [
          "Free platform access with basic features",
          "Drop shipping capabilities",
          "Private label products",
          "Basic customer support",
        ],
        popular: false,
        description: "Perfect for beginners starting their journey",
      },
      {
        name: "Basic Plan",
        price: { monthly: 179, yearly: 2148 },
        earlyAdopters: "1-17",
        features: [
          "All Starter Plan benefits",
          "Social media promotion",
          "Basic marketing templates",
          "Enhanced support",
        ],
        popular: false,
        description: "Ideal for growing businesses",
      },
      {
        name: "Growth Plan",
        price: { monthly: 311, yearly: 3732 },
        earlyAdopters: "1-15",
        features: [
          "All Basic Plan benefits",
          "Free listing optimization",
          "Personalized consultations",
          "Advanced analytics",
        ],
        popular: true,
        description: "Most popular for scaling businesses",
      },
      {
        name: "Premium Plan",
        price: { monthly: 1199, yearly: 14388 },
        earlyAdopters: "1-11",
        features: [
          "All Growth Plan benefits",
          "Free 3 months shipping",
          "Premium marketing campaigns",
          "Priority support",
        ],
        popular: false,
        description: "For established enterprises",
      },
      {
        name: "Elite Plan",
        price: { monthly: 1499, yearly: 17988 },
        earlyAdopters: "1-8",
        features: [
          "All Premium Plan benefits",
          "Exclusive marketplace promotions",
          "Personal account manager",
          "VIP treatment",
        ],
        popular: false,
        description: "Elite level service and support",
      },
      {
        name: "Platinum Plan",
        price: { monthly: 1999, yearly: 23988 },
        earlyAdopters: "1-5",
        features: [
          "All Elite Plan benefits",
          "Custom business solutions",
          "Dedicated support team",
          "White-glove service",
        ],
        popular: false,
        description: "Ultimate premium experience",
      },
    ],

    // Dynamic FAQ Data
    faqs: [
    

      {
        title: "Can I select my shipping carrier?",
        desc: "Yes, you can choose from multiple shipping carriers during checkout, each with different pricing and delivery timeframes to suit your needs.",
      },
      {
        title: "Are there any extra shipping charges?",
        desc: "All shipping costs are calculated and displayed upfront. There are no hidden fees - what you see at checkout is what you pay.",
      },
      {
        title: "Can I track my package?",
        desc: "You'll receive tracking information once your order ships, allowing you to monitor your package's progress in real-time.",
      },
      {
        title: "What's the return policy for Drop Shipping?",
        desc: "We offer flexible return policies for Drop Shipping orders. Items can be returned within 30 days of delivery in original condition.",
      },
      {
        title: "Can I return Private Label products?",
        desc: "Private Label products have specific return policies due to their customized nature. Please contact our support team for assistance with Private Label returns.",
      },
      {
        title: "How do I request a refund?",
        desc: "To request a refund, contact our customer support team with your order details. Refunds are processed according to our return policy terms.",
      },
      {
        title: "Do I have a warranty on products?",
        desc: "Yes, all products come with quality guarantees. Warranty terms vary by product type and are clearly specified in the product description.",
      },
      {
        title: "How do I create a buyer account?",
        desc: "Creating an account is simple - click 'Sign Up', provide your basic information, verify your email, and you're ready to start shopping.",
      },
      {
        title: "Do I have access to 24/7 customer support?",
        desc: "Yes, we provide 24/7 customer support through multiple channels including live chat, email, and phone for all our registered users.",
      },

    ],

    // Dynamic Service Cards Data
    serviceCards: [
      {
        title: "Drop Shipping",
        description:
          "Source premium handcrafted Kashmiri products through drop shipping, white-label, and seamless fulfillment.",
        icon: "shoppingCart",
        featured: true,
      },
      {
        title: "Consignment",
        description: "Connect consignees with consignors for risk-free Kashmiri handicraft inventory management.",
        icon: "handshake",
        featured: false,
      },
      {
        title: "Exhibition",
        description:
          "Partner with Kashmir vendor exhibitions, secure brand sponsorship in premier US handicrafts expo.",
        icon: "building",
        featured: false,
      },
      {
        title: "Import Export",
        description: "Import luxury, premium, world-renowned Kashmiri handicrafts for high-end clientele in the USA.",
        icon: "plane",
        featured: false,
      },
      {
        title: "Subsidiary",
        description: "Join the DKC USA Buyer Network for strategic and high-value partnerships in luxury handicrafts.",
        icon: "warehouse",
        featured: false,
      },
      {
        title: "Brick & Mortar",
        description:
          "Enable U.S. stores, integrate Kashmiri vendors, optimizing resources & showcasing luxury handicrafts.",
        icon: "store",
        featured: false,
      },
      {
        title: "Franchise",
        description: "Partner with or own a DKC franchise in the USA, showcasing authentic Kashmiri handicrafts.",
        icon: "home",
        featured: false,
      },
    ],
  }


  return (
    <div>
      <VerticalHeroSlider />
      <InsidePartnership {...homePageData}/>
    </div>
  )
}
